services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/America/New_York
    volumes:
      - /home/bpelleti/docker-compose:/config
    ports:
      - 81:80
      - 444:443
    restart: unless-stopped
